Documentation:
  Enabled: false

Metrics:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Security/Open:
  Enabled: false

Layout/IndentHash:
  Enabled: false
